steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/partalog/partalog/web:latest
      - -f
      - frontend/katalogcu-frontend/Dockerfile.cloudrun
      - frontend/katalogcu-frontend
images:
  - europe-west1-docker.pkg.dev/partalog/partalog/web:latest
