substitutions:
  _REGION: europe-west1
  _REPOSITORY: partalog
  _IMAGE_NAME: partalog-ai-chat
  _TAG: latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:${_TAG}
      - -f
      - Dockerfile.chat
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:${_TAG}
